### ISSUE TITLE
Include Certificate in repository

### ISSUE THREAD

**Issue by ravetroll** [IdentityServer/IdentityServer4.Demo#1]
I am attempting to get this demo to work in Azure Web App.  I can't seem to make it work with a self signed certificate that I upload into the Azure Web App SSL blade.  I have tried with a brand new service plan and web app.  Apart from the certificate I am using, my implementation is an unmodified version of this repo.  If I do modify the command AddSigningCredential to AddTemporarySigningCredential the application works correctly.  This suggests that there is something going wrong related to the signing certificate I am using.  If you can provide a test certificate that you confirm works with Azure then we can take that one variable out of the equation.

**Comment by leastprivilege** [comment]
IIRC I use this one

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/Config/idsrv3test.pfx

password is: idsrv3test

**Comment by ravetroll** [comment]
Ok, I have created Web App:  http://identityserver4demorave.azurewebsites.net/

I have uploaded the certificate from https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/Config/idsrv3test.pfx
into that web app.
![certificate](https://cloud.githubusercontent.com/assets/17169071/21845835/f559af62-d7fc-11e6-9877-d075b60a859b.JPG)

`6B7ACC520305BFDB4F7252DAEB2177CC091FAAE1` is the thumbprint of that certificate.

I changed the AddSigningCredential line to:

`builder.AddSigningCredential("6B7ACC520305BFDB4F7252DAEB2177CC091FAAE1", StoreLocation.CurrentUser, nameType: NameType.Thumbprint);`

If I restart the app and then request the homepage I do see the following exception:

```
2017-01-11T10:57:47  Welcome, you are now connected to log-streaming service.

2017-01-11 10:57:53.480 +00:00 [Fatal] Application startup exception

System.InvalidOperationException: certificate: '6B7ACC520305BFDB4F7252DAEB2177CC091FAAE1' not found in certificate store

   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCrypto.AddSigningCredential(IIdentityServerBuilder builder, String name, StoreLocation location, NameType nameType)

   at IdentityServer4Demo.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Brendon\Source\Repos\IdentityServer4.Demo\src\IdentityServer4Demo\Startup.cs:line 28

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()

   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

2017-01-11 10:57:53.636 +00:00 [Warning] Unable to bind to http://localhost:1533 on the IPv6 loopback interface.

System.AggregateException: One or more errors occurred. (Error -4089 EAFNOSUPPORT address family not supported) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

   at System.Threading.Tasks.Task.Wait()

   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)

   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)

---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)<---



```

That doesn't make sense though as I have loaded the certificate and you can see it on the blade.

If I go into Kudu though and run Powershell command dir `cert:\CurrentUser\My` I get nothing suggesting that the cert has not been loaded.  Am I loading the certificate in the right way?

**Comment by leastprivilege** [comment]
Have you marked the cert to be available in the VM? This is not happening by default.

**Comment by ravetroll** [comment]
I have set WEBSITE_LOAD_CERTIFICATES to * and now its working.  http://identityserver4demorave.azurewebsites.net/

I'm now going to try and use this certificate on my main app which does have WEBSITE_LOAD_CERTIFICATES to *
